#ifndef DEBUG_PRINT_CONFIG_H
#define DEBUG_PRINT_CONFIG_H

/********* CONFIGURATION FOR INDIVIDUAL MODULES
 * Enable Debug Messages	= 1
 * Disable Debug Messages	= 0
 */
#define DEBUG_ENABLE_GHDD		1
#define DEBUG_MAXLEVEL_GHDD		DBG_ERROR

#define DEBUG_ENABLE_GENL		1
#define DEBUG_MAXLEVEL_GENL		DBG_TRACE

#define DEBUG_ENABLE_ZIGBEE		1
#define DEBUG_MAXLEVEL_ZIGBEE	DBG_DEBUG

#endif //DEBUG_PRINT_CONFIG_H
