/**
 * @file mac_orphan.c
 *
 * Implements orphan scan related functionalities on coordinator side.
 *
 * $Id: mac_orphan.c,v 1.3 2014/11/26 13:19:41 ranjan Exp $
 *
 * Copyright (c) 2011, Greenvity Communication All rights reserved.
 *
 */
#ifdef HYBRII_802154

/* === Includes ============================================================ */

#include <string.h>
#include "papdef.h"
#include "timer.h"
#include "return_val.h"
#include "bmm.h"
#include "qmm.h"
#include "mac_msgs.h"
#include "mac_hal.h"
#include "mac_const.h"
#include "mac_api.h"
#include "mac_data_structures.h"
#include "mac_internal.h"
#include "mac.h"
#include "utils_fw.h"

/* === Macros  ============================================================= */


/* === Globals ============================================================= */


/* === Prototypes ========================================================== */


/* === Implementation ====================================================== */

/**
 *
 * This function processes an incoming orphan notification command.
 * A PAN coordinator gets to this function through a TAL data indication
 * message.
 *
 * buf_p - Pointer to reception buffer
 */
void mac_process_orphan_notification (buffer_t *buf_p)
{
    mlme_orphan_ind_t *moi_p = (mlme_orphan_ind_t *)BMM_BUFFER_POINTER(buf_p);

    moi_p->cmdcode = MLME_ORPHAN_INDICATION;
    ADDR_COPY_DST_SRC_64(moi_p->OrphanAddress,
                         mac_parse_data.src_addr.long_address);

    /* Append the MLME orphan indication message to MAC-NHLE queue */
#if (defined UM) && (!defined ZBMAC_DIAG)
	mlme_send_to_host(buf_p);
#else
	mlme_orphan_ind(buf_p);
#endif	
}


/**
 *
 * The MLME-ORPHAN.response primitive allows the next higher layer
 * of a coordinator to respond to the MLME-ORPHAN.indication primitive.
 * The MLME-ORPHAN.response primitive is generated by the next higher
 * layer and issued to its MLME when it reaches a decision about whether
 * the orphaned device indicated in the MLME-ORPHAN.indication primitive
 * is associated.
 *
 *  buf_p - Pointer to the message buffer.
 */
void mlme_orphan_response (buffer_t *buf_p)
{
    bool tx_status;

    tx_status = mac_tx_coord_realignment_command(ORPHANREALIGNMENT,
                                                 buf_p,
                                                 hal_pib_PANId,
                                                 hal_pib_CurrentChannel,
                                                 hal_pib_CurrentPage);

    if (tx_status == FALSE) {
        mac_mlme_comm_status(MAC_CHANNEL_ACCESS_FAILURE, buf_p);
    }
}

#endif //HYBRII_802154
